version: '3.8'

services:
  app:
    image: ksecurity/server:lastest
    volumes:
      - .docker/data:/data
    env_file: .env
    ports:
      - '${PORT}:${PORT}'
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - database-network
    healthcheck:
      test: wget --quiet --tries=1 --spider http://${HOST}:${PORT} || exit 1z
      interval: 30s
      timeout: 10s
      retries: 5

  database:
    image: mongo:6.0.5
    volumes:
      - .docker/data/db:/data/db
      - .docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
    restart: unless-stopped
    networks:
      - database-network
    healthcheck:
      test: ['CMD', 'mongosh', '--quiet', '--eval', 'db.runCommand("ping")', '-u', '${DATABASE_USERNAME}', '-p', '${DATABASE_PASSWORD}', '--port', '${DATABASE_PORT}', '${DATABASE_NAME}']
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  database-network:
    driver: bridge
